"""Compare accuracy runs across models (Slide 10) and check them against R4/R5.

    python scripts/accuracy_compare.py                         # latest run per model in results/accuracy/
    python scripts/accuracy_compare.py results/accuracy/a.csv results/accuracy/b.csv

Reads the per-ticket CSVs written by accuracy_test.py and writes results/accuracy/comparison.md:
overall accuracy, per-category recall and precision, R4 (overall >= 85%) and R5 (every category
>= 70% recall) verdicts, and single-request latency (p50/p95 of successful requests).
"""

import argparse
from pathlib import Path

from common import CATEGORIES, REPO, md_table, percentile, read_csv

RESULTS = REPO / "results" / "accuracy"
R4_MIN, R5_MIN = 0.85, 0.70  # planning/requirements.md


def latest_per_model():
    latest = {}
    for path in sorted(RESULTS.glob("*.csv")):  # names start with a UTC timestamp, so later wins
        rows = read_csv(path)
        model = next((r["model"] for r in rows if r["model"]), None)
        if model:
            latest[model] = path
    return list(latest.values())


def score(path):
    rows = read_csv(path)
    n = len(rows)
    correct = sum(r["correct"] == "Y" for r in rows)
    recall, precision = {}, {}
    for c in CATEGORIES:
        support = [r for r in rows if r["golden"] == c]
        predicted = [r for r in rows if r["predicted"] == c]
        recall[c] = sum(r["correct"] == "Y" for r in support) / len(support) if support else None
        precision[c] = sum(r["golden"] == c for r in predicted) / len(predicted) if predicted else None
    lat = [float(r["latency_ms"]) / 1000 for r in rows if r["status"] == "200"]
    return {
        "model": next((r["model"] for r in rows if r["model"]), "?"),
        "digest": next((r["model_digest"] for r in rows if r["model_digest"]), "")[:19],
        "file": path.name, "n": n, "acc": correct / n if n else 0,
        "failed": sum(r["status"] != "200" for r in rows),
        "recall": recall, "precision": precision,
        "p50": percentile(lat, 50), "p95": percentile(lat, 95),
    }


def pct(x):
    return "n/a" if x is None else f"{x:.1%}"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csvs", nargs="*", help="accuracy_test.py result CSVs (default: latest per model)")
    args = ap.parse_args()
    paths = [Path(p) for p in args.csvs] or latest_per_model()
    if not paths:
        raise SystemExit(f"No accuracy results in {RESULTS}. Run scripts/accuracy_test.py first.")

    runs = [score(p) for p in paths]
    for r in runs:
        r["r4"] = r["acc"] >= R4_MIN
        worst = min((v, c) for c, v in r["recall"].items() if v is not None)
        r["worst"] = worst
        r["r5"] = worst[0] >= R5_MIN

    lines = [
        "# Accuracy comparison", "",
        "Generated by `scripts/accuracy_compare.py` from: " + ", ".join(f"`{r['file']}`" for r in runs), "",
        "## Overall, against R4 (>= 85%) and R5 (every category >= 70% recall)", "",
        md_table(["Model", "Digest", "Tickets", "Overall accuracy", "R4", "Weakest category", "R5",
                  "Latency p50", "Latency p95"],
                 [[r["model"], f"`{r['digest']}`", r["n"] - r["failed"] if not r["failed"] else f"{r['n']} ({r['failed']} failed)",
                   f"**{pct(r['acc'])}**", "PASS" if r["r4"] else "FAIL",
                   f"{r['worst'][1]} {pct(r['worst'][0])}", "PASS" if r["r5"] else "FAIL",
                   f"{r['p50']:.2f} s" if r["p50"] else "n/a", f"{r['p95']:.2f} s" if r["p95"] else "n/a"]
                  for r in runs]), "",
        "## Per-category recall (share of each golden category classified correctly)", "",
        md_table(["Category"] + [r["model"] for r in runs],
                 [[c] + [("FAIL " if (v := r["recall"][c]) is not None and v < R5_MIN else "") + pct(v) for r in runs]
                  for c in CATEGORIES]), "",
        "## Per-category precision (share of each predicted category that was right)", "",
        md_table(["Category"] + [r["model"] for r in runs],
                 [[c] + [pct(r["precision"][c]) for r in runs] for c in CATEGORIES]), "",
        "Confusion matrices: see each run's own report (`results/accuracy/<run>.md`).", "",
    ]
    out = RESULTS / "comparison.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"Wrote {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
