"""Write the readable labelling protocol (golden/PROTOCOL.md) from labeler/protocol.json.

    python scripts/export_protocol.py           # regenerate after every protocol.json change
    python scripts/export_protocol.py --check   # exit 1 if PROTOCOL.md is out of date

protocol.json is the single source of truth: the labelling app shows the same definitions.
Optional keys it understands besides definitions/tie_break/revisions:
    "edge_cases": [{"rule": "...", "example_rows": [3022, 3107]}]
"""

import argparse
import json
import sys

from common import NONE_LABEL, REPO

SOURCE = REPO / "labeler" / "protocol.json"
OUT = REPO / "golden" / "PROTOCOL.md"


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(p):
    defs = p.get("definitions", {})
    lines = [
        "# Labelling protocol",
        "",
        f"**Current version:** {p.get('version', '?')}",
        "",
        "> Generated from `labeler/protocol.json` by `scripts/export_protocol.py`. Do not edit this file by hand;",
        "> edit `protocol.json` and regenerate. Earlier versions are in the git history of both files.",
        "",
        "## Purpose",
        "",
        "This protocol defines how the team labels complaint tickets for the golden test set, which is used to "
        "measure each candidate model's classification accuracy. The dataset's own labels were chosen by consumers "
        "and are unreliable, so every golden-set label comes from this protocol instead.",
        "",
        "## Procedure",
        "",
        "1. Every ticket is labelled by **at least two team members independently**, without conferring, using the "
        "labelling app (`labeler/`). Each person's labels are saved to their own sheet.",
        "2. The app shows only the ticket text and row number. The dataset's original labels are hidden so they "
        "cannot bias the labeller.",
        "3. Labellers do not ask any AI model which category a ticket belongs to. Looking up unfamiliar terms or "
        "company names is allowed.",
        "4. For each ticket the labeller records:",
        f"   - **Label:** one of the seven categories below, or *{NONE_LABEL}*",
        "   - **Also fits** (optional): a second category the ticket could reasonably belong to",
        "   - **Reasoning:** a short explanation, especially for doubtful cases",
        "5. The protocol is not changed while a labelling round is in progress. Gaps are noted in the reasoning and "
        "resolved afterwards.",
        "6. After labelling, agreement is measured (Cohen's kappa per pair of labellers; Fleiss' kappa for groups "
        "of three or more). Every disagreement is discussed and resolved, with the reason recorded. If a group "
        "cannot agree, a team member who did not label those rows acts as tie-breaker.",
        "7. Where a disagreement reveals a gap in this protocol, a rule is added and the version is bumped "
        "(see the revision log).",
        "8. A ticket may be **excluded** from the golden set if it cannot be assigned to one of the seven "
        "categories; each exclusion and its reason is recorded.",
        "",
        "## Categories",
        "",
        "| # | Category | Definition |",
        "|---|---|---|",
    ]
    real = [(c, d) for c, d in defs.items() if c != NONE_LABEL]
    lines += [f"| {i} | **{cell(c)}** | {cell(d)} |" for i, (c, d) in enumerate(real, 1)]
    if NONE_LABEL in defs:
        lines += ["", f"**{NONE_LABEL}** (labelling only): {defs[NONE_LABEL]}"]

    lines += ["", "## Deciding between categories", ""]
    if p.get("tie_break"):
        lines += [f"**Tie-break rule:** {p['tie_break']}", ""]
    edge = p.get("edge_cases", [])
    if edge:
        lines += ["**Edge-case rules:**", ""]
        for e in edge:
            rows = e.get("example_rows") or []
            lines.append(f"- {e['rule']}" + (f" (e.g. rows {', '.join(map(str, rows))})" if rows else ""))
        lines.append("")
    else:
        lines += ["No edge-case rules yet. They are added here as disagreements are resolved.", ""]

    lines += ["## Revision log", "", "| Version | Date | Change | Triggered by rows |", "|---|---|---|---|"]
    for r in p.get("revisions", []):
        rows = ", ".join(map(str, r.get("triggered_by_rows") or [])) or "n/a"
        lines.append(f"| {cell(r.get('version', ''))} | {cell(r.get('date', ''))} | {cell(r.get('change', ''))} | {rows} |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only check that PROTOCOL.md is up to date")
    args = ap.parse_args()

    protocol = json.loads(SOURCE.read_text(encoding="utf-8"))
    text = render(protocol)
    latest = (protocol.get("revisions") or [{}])[-1].get("version")
    if latest and not str(protocol.get("version", "")).startswith(latest):
        print(f"WARNING: version is {protocol.get('version')!r} but the last revision entry is {latest!r}. "
              "Add a revisions entry for every version.")

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(REPO)} is out of date. Run: python scripts/export_protocol.py")
            sys.exit(1)
        print(f"{OUT.relative_to(REPO)} is up to date ({protocol.get('version')}).")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"Wrote {OUT.relative_to(REPO)} (protocol {protocol.get('version')}).")


if __name__ == "__main__":
    main()
